# Generated by Django 4.2.11 on 2024-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(choices=[(0, 'STATERS'), (1, 'MAINS'), (2, 'SIDES'), (3, 'DESSERTS'), (4, 'SNACKS')], default=0),
        ),
    ]
