# Generated by Django 4.2.11 on 2024-03-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_recipe_serving_alter_recipe_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
